language: php

stages:
  - SQLite (with redis)
  - SQLite (with memcached)

services:
  - memcached
  - redis

before_script:
  - pecl install pcov
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - if [[ $COVERAGE == "yes" ]]; then ./cc-test-reporter before-build; fi
  - composer install

jobs:
  include:
    - stage: SQLite (with redis)
      php: 7.3
      env: CACHE_DRIVER=redis

    - stage: SQLite (with redis)
      php: 7.4
      env: CACHE_DRIVER=redis

    - stage: SQLite (with redis)
      php: 'nightly'
      env: CACHE_DRIVER=redis

    - stage: SQLite (with memcached)
      php: 7.3
      env: CACHE_DRIVER=memcached

    - stage: SQLite (with memcached)
      php: 7.4
      env: CACHE_DRIVER=memcached

    - stage: SQLite (with memcached)
      php: 'nightly'
      env: CACHE_DRIVER=memcached

  allow_failures:
    - php: 'nightly'

script:
  - ./vendor/bin/phpunit --coverage-xml=build/coverage-xml --log-junit=build/junit.xml
  - if [[ $COVERAGE == "yes" ]]; then ./vendor/bin/infection --coverage=build --min-msi=60 -j$(nproc); fi

after_success:
  - if [[ $COVERAGE == "yes" ]]; then ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT; fi
  - bash <(curl -s https://codecov.io/bash)
